techpack: touch: Drop CONFIG_TOUCHSCREEN_ST
Not used by Metroid and causes duplicate symbols :-

ld.lld: error: duplicate symbol: fts_read
>>> defined at focaltech_spi_v2.c:249 (/home/abhay/Downloads/meteoric_np3/out/../techpack/touch-drivers/focaltech_tp/focaltech_spi_v2.c:249)
>>>            techpack/touch-drivers/focaltech_tp/focaltech_spi_v2.o:(fts_read) in archive vmlinux.a
>>> defined at ftsIO.c:247 (/home/abhay/Downloads/meteoric_np3/out/../techpack/touch-drivers/st/fts_lib/ftsIO.c:247)
>>>            techpack/touch-drivers/st/fts_lib/ftsIO.o:(.text+0x418) in archive vmlinux.a

ld.lld: error: duplicate symbol: fts_write
>>> defined at focaltech_spi_v2.c:158 (/home/abhay/Downloads/meteoric_np3/out/../techpack/touch-drivers/focaltech_tp/focaltech_spi_v2.c:158)
>>>            techpack/touch-drivers/focaltech_tp/focaltech_spi_v2.o:(fts_write) in archive vmlinux.a
>>> defined at ftsIO.c:400 (/home/abhay/Downloads/meteoric_np3/out/../techpack/touch-drivers/st/fts_lib/ftsIO.c:400)
>>>            techpack/touch-drivers/st/fts_lib/ftsIO.o:(.text+0xccc) in archive vmlinux.a

Signed-off-by: HELLBOY017 <abhaygill017@gmail.com>